services:
  backend:
    build: ./backend
    volumes:
      - ./data-psc:/app/data-psc
      - ./data-sap-zmmm_open_bo:/app/data-sap-zmmm_open_bo
      - ./data-partviz:/app/data-partviz
      - ./data-sap-zvsd_parts_progress-order_item:/app/data-sap-zvsd_parts_progress-order_item
      - ./data-sap-zvsd_parts_progress-source_item:/app/data-sap-zvsd_parts_progress-source_item
      - ./data-sap-zvsd_parts_progress:/app/data-sap-zvsd_parts_progress
      - ./data-so-exclude:/app/data-so-exclude
      - ./output:/app/output
    environment:
      CORS_ORIGINS: "*"
      PROJECT_ROOT: /app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ""
    ports:
      - "8080:80"
    depends_on:
      - backend
